"""Offline tests for the shared job-system readers (jobsearch/boards.py).

The important one is test_history_keys_are_unchanged: tests/fixtures/readers/
golden_keys.json holds the keys the two searches stored BEFORE the readers were
merged into one library (generated by running the old code against the same
fake answers). If a reader ever builds a different key, every tracked role
would look closed-and-reopened, so that must never drift.
"""
import json
import pathlib
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

import fakenet                                    # noqa: E402
from jobsearch import adapters, boards as B       # noqa: E402
from jobsearch.http import FetchError, NotFound   # noqa: E402

ROUTES = json.loads((ROOT / "tests/fixtures/readers/payloads.json").read_text())
GOLDEN = json.loads((ROOT / "tests/fixtures/readers/golden_keys.json").read_text())

WEEKLY = {
    "greenhouse": ("acme", {}), "lever": ("acme", {}), "ashby": ("acme", {}), "workable": ("acme", {}),
    "smartrecruiters": ("Acme", {}), "bamboohr": ("acme", {}), "breezy": ("acme", {}),
    "recruitee": ("acme", {}), "rippling": ("acme", {}), "jobvite": ("acme-internal", {}),
    "workday": ("acme", {"wd": "wd5", "site": "External", "confidence": "html", "careers_url": "x"}),
}
OPCO = {
    "greenhouse": ("acme", {}), "lever": ("acme", {}), "ashby": ("acme", {}), "workable": ("acme", {}),
    "smartrecruiters": ("Acme", {}), "recruitee": ("acme", {}), "breezy": ("acme", {}), "bamboohr": ("acme", {}),
    "workday": ("acme", {"host": "acme.wd5.myworkdayjobs.com", "site": "External"}),
    "ukg": ("ACM1000ACME", {"host": "recruiting2.ultipro.com", "board": "82898216-ca7a-4621-b01b-bf3410c919b2"}),
    "adp": ("0b0b0b0b-1111-2222-3333-444444444444", {"cc": "19000101_000001"}),
    "dayforce": ("acme", {"board": "CANDIDATEPORTAL"}),
}


def test_history_keys_are_unchanged():
    with fakenet.serve(ROUTES):
        for name, (slug, kw) in WEEKLY.items():
            keys = sorted(j["job_key"] for j in adapters.ADAPTERS[name](slug, **kw))
            if name == "jobvite":      # now also reads page 2; the old keys must all still be there
                assert set(GOLDEN["weekly"][name]) <= set(keys), name
            else:
                assert keys == GOLDEN["weekly"][name], name
        for name, (slug, kw) in OPCO.items():
            ids = sorted(B.opco_id(j) for j in B.READERS[name](slug, **kw) if j["title"])
            assert ids == GOLDEN["opco"][name], name


def test_every_job_has_title_and_direct_link():
    with fakenet.serve(ROUTES):
        for name, (slug, kw) in {**OPCO, "rippling": ("acme", {}), "jobvite": ("acme-internal", {})}.items():
            for j in B.READERS[name](slug, **kw):
                if j["title"]:
                    assert j["url"].startswith("https://"), (name, j)
                    assert j["system"] == name and j["id"]


def test_jobvite_follows_next_page():
    with fakenet.serve(ROUTES):
        jobs = B.jobvite("acme-internal")
    assert [j["id"] for j in jobs] == ["oltHAfwP", "oo2uAfwe", "oPage2Job"]
    assert jobs[0]["title"] == "Senior Account Executive" and jobs[0]["location"] == "Santa Barbara, CA"


def test_lever_tells_a_missing_board_from_an_empty_one():
    with fakenet.serve(ROUTES):
        assert B.lever("quiet") == []                 # real board, nothing open
        with pytest.raises(NotFound):                 # board no longer exists
            B.lever("ghost")


def test_paylocity_reads_the_list_inside_the_page():
    with fakenet.serve(ROUTES):
        jobs = B.paylocity("5e5fc082-a90b-4d93-8b73-46f77d40e081")
    assert [(j["id"], j["title"]) for j in jobs] == [("4375500", "Assistant Portfolio Manager"),
                                                      ("4561431", "Director of Marketing")]   # internal-only skipped
    assert jobs[0]["url"] == "https://recruiting.paylocity.com/Recruiting/Jobs/Details/4375500"
    assert jobs[0]["location"] == "Kansas City, MO" and jobs[0]["posted"] == "2026-10-08"
    assert jobs[1]["location"] == "Remote · Denver, CO"


def test_icims_pages_until_a_page_adds_nothing():
    with fakenet.serve(ROUTES) as calls:
        jobs = B.icims("careers-acme", host="careers-acme.icims.com")
    assert [j["id"] for j in jobs] == ["14675", "14658", "14601"]
    assert jobs[0]["title"] == "Account Rep I" and jobs[0]["location"] == "US-MA-Boston"
    assert jobs[0]["url"] == "https://careers-acme.icims.com/jobs/14675/account-rep-i/job"
    assert sum("pr=" in c for c in calls) == 3      # pages 0, 1, then the empty page 2


def test_breezy_on_a_company_address():
    with fakenet.serve(ROUTES):
        jobs = B.breezy("jobs.acmehomes.com", origin="https://jobs.acmehomes.com")
    assert [j["title"] for j in jobs] == ["Photographer"]


def test_workday_keeps_relative_date_and_requisition():
    with fakenet.serve(ROUTES):
        jobs = B.workday("acme", wd="wd5", site="External")
    assert len(jobs) == 2 and jobs[0]["posted_rel"] == "Posted 3 Days Ago" and jobs[0]["ref"] == "R0012345"
    assert jobs[0]["url"] == "https://acme.wd5.myworkdayjobs.com/External/job/Remote/Director--Investments_R0012345"


def test_missing_board_is_an_error_not_an_empty_list():
    """Where the job system answers 404 for an unknown board, the reader must say
    "missing", never "no openings"."""
    with fakenet.serve(ROUTES):
        for name in ("greenhouse", "ashby", "workable", "rippling", "paylocity"):
            with pytest.raises(FetchError):
                B.READERS[name]("no-such-board")


CLASSIFY = [
    ("https://jobs.dayforcehcm.com/abhi/CANDIDATEPORTAL", "dayforce", "abhi"),
    ("https://apply.workable.com/belong-6", "workable", "belong-6"),
    ("https://recruiting2.ultipro.com/LAM1000LAC/JobBoard/82898216-ca7a-4621-b01b-bf3410c919b2/?q=", "ukg", "LAM1000LAC"),
    ("https://wework.wd1.myworkdayjobs.com/WeWork", "workday", "wework"),
    ("https://x.wd1.myworkdayjobs.com/wday/cxs/x/livebhcareers/jobs", "workday", "x"),
    ("https://job-boards.greenhouse.io/embed/job_board?for=evergreen&b=1", "greenhouse", "evergreen"),
    ("https://boards.greenhouse.io/embed/job_board/js?for=kasa", "greenhouse", "kasa"),
    ("https://boards-api.greenhouse.io/v1/boards/kasa/jobs", "greenhouse", "kasa"),
    ("https://api.ashbyhq.com/posting-api/job-board/certifid", "ashby", "certifid"),
    ("https://recruiting.paylocity.com/recruiting/jobs/All/5e5fc082-a90b-4d93-8b73-46f77d40e081", "paylocity",
     "5e5fc082-a90b-4d93-8b73-46f77d40e081"),
    ("https://careers-realpagepms.icims.com/jobs/search?ss=1", "icims", "careers-realpagepms"),
    ("https://ats.rippling.com/rentspree/jobs", "rippling", "rentspree"),
    ("https://jobs.gem.com/bilt", "gem", "bilt"),
    ("https://oakbrookcorp.isolvedhire.com/jobs/", "isolved", "oakbrookcorp"),
    ("https://www.medicalpropertiestrust.com/careers", "page", ""),
    ("https://apply.workable.com/j/996A05186B", "page", ""),          # a single posting, not a board
    ("https://www.gem.com/form", "page", ""),                          # marketing site, not a board
]


@pytest.mark.parametrize("url,system,slug", CLASSIFY)
def test_classify(url, system, slug):
    board = B.classify(url)
    assert (board.system, board.slug) == (system, slug)


BASELINE_IDENTITIES = {
    # Column D -> the identity stored with that company's roles in state/opco/baseline.json
    # when the readers were merged. If classify() ever gives a different one, that company's
    # history restarts.
    "https://jobs.dayforcehcm.com/abhi/CANDIDATEPORTAL": 'dayforce:abhi:{"board": "CANDIDATEPORTAL"}',
    "https://apply.workable.com/belong-6": "workable:belong-6:{}",
    "https://eprproperties.bamboohr.com/careers": "bamboohr:eprproperties:{}",
    "https://recruiting2.ultipro.com/LAM1000LAC/JobBoard/82898216-ca7a-4621-b01b-bf3410c919b2/?q=&o=postedDateDesc":
        'ukg:LAM1000LAC:{"board": "82898216-ca7a-4621-b01b-bf3410c919b2", "host": "recruiting2.ultipro.com"}',
    "https://www.medicalpropertiestrust.com/careers": 'page::{"url": "https://www.medicalpropertiestrust.com/careers"}',
    "https://jobs.realpropertymgt.com/jobs": 'page::{"url": "https://jobs.realpropertymgt.com/jobs"}',
    "https://wework.wd1.myworkdayjobs.com/WeWork": 'workday:wework:{"host": "wework.wd1.myworkdayjobs.com", "site": "WeWork"}',
}


def test_classify_identity_matches_the_saved_baseline():
    for column_d, key in BASELINE_IDENTITIES.items():
        assert B.classify(column_d).key == key


def test_same_board_spelled_differently_has_one_identity():
    old = B.Board("workday", "zillow", {"wd": "wd5", "site": "Zillow_Group_External"})
    new = B.classify("https://zillow.wd5.myworkdayjobs.com/en-US/Zillow_Group_External")
    assert old.identity() == new.identity()
    assert B.Board("lever", "Acme").identity() == B.Board("lever", "acme").identity()
    assert B.Board("greenhouse", "acme").identity() != B.Board("greenhouse", "acmeinc").identity()


@pytest.mark.parametrize("url", [
    "https://assets-cdn.breezy.hr/x.css", "https://marketing.breezy.hr/", "https://images4.bamboohr.com/1/logo.png",
    "https://partners.bamboohr.com/", "https://blog.recruitee.com/x", "https://cdn01.icims.com/a.js",
    "https://community.icims.com/", "https://jobs.smartrecruiters.com/oneclick-ui/company/x",
    "https://jobs.dayforcehcm.com/_next/static/x.js", "https://apply.workable.com/_next/x",
    "https://ats.rippling.com/_next/static", "https://jobs.jobvite.com/__assets__/x",
    "https://acme.wd1.myworkdayjobs.com/wday/authgwy/acme/login.htmld",
])
def test_vendor_asset_and_marketing_addresses_are_not_boards(url):
    assert B.classify(url).system == "page"


def test_classify_is_fast_on_very_long_addresses():
    import time
    started = time.time()
    B.classify("https://jobs.lever.co/" + "a" * 20000)
    B.classify("https://example.com/?token=" + "a" * 20000)
    assert time.time() - started < 0.5


def test_paycom_and_paylocity_links_without_a_board_id_are_not_readable():
    for url in ("https://recruiting.paylocity.com/Recruiting/Jobs/Details/4375500",
                "https://www.paycomonline.net/v4/ats/web.php/jobs"):
        board = B.classify(url)
        assert board.system in ("paylocity", "paycom") and not board.readable and not board.rendered


@pytest.mark.parametrize("url,system,slug", [
    ("https://job-boards.greenhouse.io/public", "greenhouse", "public"),
    ("https://jobs.lever.co/go", "lever", "go"),
    ("https://jobs.ashbyhq.com/build", "ashby", "build"),
    ("https://sales.bamboohr.com/careers", "bamboohr", "sales"),
])
def test_ordinary_words_can_be_company_boards(url, system, slug):
    board = B.classify(url)
    assert (board.system, board.slug) == (system, slug)


def test_comeet_feed_and_its_address():
    board = B.classify("https://www.comeet.co/careers-api/2.0/company/3E.006/positions?token=ABC123&details=false")
    assert (board.system, board.slug, board.params) == ("comeet", "3E.006", {"key": "ABC123"})
    with fakenet.serve(ROUTES):
        jobs = B.read_board(board)
    assert [(j["id"], j["title"], j["location"]) for j in jobs] == [("3E.275", "Account Executive (SMB)", "Miami (US)")]
    assert jobs[0]["url"] == "https://www.acme.test/job-post?job=3E.275"


def test_smartrecruiters_tells_a_missing_company_from_an_empty_one():
    with fakenet.serve(ROUTES):
        assert B.smartrecruiters("QuietCo") == []
        with pytest.raises(NotFound):
            B.smartrecruiters("NoSuchCo")


def test_gems_own_embed_script_is_not_a_company_board():
    assert B.classify("https://jobs.gem.com/gem/embed.js").system == "page"
    assert B.classify("https://jobs.gem.com/lower-llc").slug == "lower-llc"
